###
POST http://localhost:8070/message
Content-Type: application/json

{
  "user_id": "12345",
  "username": "testuser",
  "content": "hello man",
  "pub_key": "1081381308",
  "hash": "hash1234567890",
}